//------------------------------------------------------------------------------
// This file is automatically generated by dot42
//------------------------------------------------------------------------------

namespace BitcoinAverage._42
{
    using System;
    
    
    public sealed class R
    {
        
        public sealed class Layouts
        {
            
            public const int MainLayout = 0x7f020000;
        }
        
        public sealed class Ids
        {
            
            public const int tableLayout1 = 0x7f030035;
            
            public const int tableRow1 = 0x7f030036;
            
            public const int textView10 = 0x7f030037;
            
            public const int txtLastPrice = 0x7f030038;
            
            public const int tableRow2 = 0x7f030039;
            
            public const int textView12 = 0x7f03003a;
            
            public const int txtAsk = 0x7f03003b;
            
            public const int tableRow3 = 0x7f03003c;
            
            public const int textView13 = 0x7f03003d;
            
            public const int txtBid = 0x7f03003e;
            
            public const int tableRow4 = 0x7f03003f;
            
            public const int txtVolume = 0x7f030040;
            
            public const int tableRow5 = 0x7f030041;
            
            public const int txtAvg = 0x7f030042;
        }
    }
}
